<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="forearm_radius" value="0.02" />    
    <xacro:property name="forearm_length" value="0.3" />
    <xacro:property name="hand_radius" value="0.02" />    
    <xacro:property name="hand_length" value="0.3" />

    <link name="arm_base_link">
        <visual>
            <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0" />
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <material name="orange" />
        </visual>

        <xacro:box_inertia m="0.5" 
                           l="${2.0 * arm_base_length}" 
                           w="${2.0 * arm_base_width}" 
                           h="${2.0 * arm_base_height}"
                           xyz="0 0 ${arm_base_height / 2.0}" 
                           rpy="0 0 0" />

        <collision>
            <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0" />
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
        </collision>
    </link>


    <link name="forearm_link">
        <visual>
            <origin xyz="0 0 ${forearm_length / 2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <material name="yellow" />
        </visual>

        <xacro:cylinder_inertia m="0.3" 
                                r="${2.0 * forearm_radius}" 
                                h="${2.0 * forearm_length}" 
                                xyz="0 0 ${forearm_length / 2}" 
                                rpy="0 0 0" />

        <collision>
            <origin xyz="0 0 ${(forearm_length / 2)}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
        </collision>
    </link>


    <link name="hand_link">
        <visual>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <material name="yellow" />
        </visual>

        <xacro:cylinder_inertia m="0.3" 
                                r="${2.0 * hand_radius}" 
                                h="${2.0 * hand_length}" 
                                xyz="0 0 ${hand_length / 2.0}" 
                                rpy="0 0 0" />

        <collision>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
        </collision>
    </link> 

    <joint name="arm_base_forearm_joint" type="revolute">
        <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0" />

        <parent link="arm_base_link"/>
        <child link="forearm_link"/>

        <limit effort="100" velocity="100" lower="0" upper="${pi / 2.0}" />
        <dynamics damping="0.1" friction="0.05"/>
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0"/>
        <axis xyz="0 1 0" />

        <parent link="forearm_link"/>
        <child link="hand_link"/>

        <limit effort="100" velocity="100" lower="0" upper="${pi / 2.0}" />
        <dynamics damping="0.1" friction="0.05"/>
    </joint>


  

</robot>