<?xml version="1.0"?>
<robot name="mobile_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename ="common_properties.urdf.xacro" />
    <xacro:include filename ="base.urdf.xacro" />
    <xacro:include filename ="base_gazebo.xacro" />
    <xacro:include filename ="arm.xacro" />
    <xacro:include filename ="arm_gazebo.xacro" />

    <joint name="base_arm_joint" type="fixed">
        <parent link="base_link" />

        <child link="arm_base_link" />

        <origin xyz="${base_length / 4.0} 0 ${base_height / 2.0}" rpy="0 0 0" />
    </joint>  
    
    <!-- <xacro:include filename ="camera.xacro" /> -->

</robot>